#!/bin/bash
# DagLock Testnet Deployment Script
# Usage: ./scripts/deploy-testnet.sh

set -e

echo "=== DagLock Testnet Deployment ==="

# Check prerequisites
echo "Checking prerequisites..."
command -v cargo >/dev/null 2>&1 || { echo "Error: cargo not found. Install Rust."; exit 1; }
command -v node >/dev/null 2>&1 || { echo "Error: node not found. Install Node.js."; exit 1; }

# Build indexer
echo "Building indexer..."
cargo build --release -p daglock-indexer

# Template hashes for UTXO detection
# Generated by: cargo test -p daglock-contracts -- print_template_hashes --nocapture
# These identify DagLock UTXOs regardless of constructor parameters
DAGLOCK_KAS_TEMPLATE="30876e3ea42d0e23bb0980f3fd97ae8807e9c70f"
DAGLOCK_ARBITER_TEMPLATE="c6d10350b51d5fedcc05382d02d8334a783be220"
DAGLOCK_KRC20_TEMPLATE="8a43a8438d183a92bc7b94337c031196ff16725b"

# Copy config
echo "Writing template hashes to .env..."
cat > .env << ENVEOF
DAGLOCK_KAS_TEMPLATE=$DAGLOCK_KAS_TEMPLATE
DAGLOCK_ARBITER_TEMPLATE=$DAGLOCK_ARBITER_TEMPLATE
DAGLOCK_KRC20_TEMPLATE=$DAGLOCK_KRC20_TEMPLATE
DAGLOCK_MESSAGE_KEY=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")
ENVEOF

# Extract template hashes for reference
echo "Template hashes extracted:"
echo "  KAS:   $DAGLOCK_KAS_TEMPLATE"
echo "  ARB:   $DAGLOCK_ARBITER_TEMPLATE"
echo "  KRC20: $DAGLOCK_KRC20_TEMPLATE"
echo ""

# Install bot dependencies
echo "Installing bot dependencies..."
cd bot && npm install && cd ..

# Install web dependencies
echo "Installing web dependencies..."
cd web && npm install && npm run build && cd ..

echo ""
echo "=== Build Complete ==="
echo ""
echo "To run:"
echo "  source .env"
echo "  docker build -t daglock/indexer . && docker run -p 8543:8543 \\"
echo "    --env-file .env daglock/indexer --host 0.0.0.0"
echo ""
echo "Or directly:"
echo "  cargo run -p daglock-indexer -- \\"
echo "    --wrpc-url ws://your-kaspa-node:17110 \\"
echo "    --daglock-kas-template \$DAGLOCK_KAS_TEMPLATE \\"
echo "    --daglock-krc20-template \$DAGLOCK_KRC20_TEMPLATE \\"
echo ""
echo "For detailed instructions, see docs/DEPLOYMENT.md"
