[package]
name = "daglock-wasm-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
js-sys.workspace = true
web-sys.workspace = true
getrandom.workspace = true
serde.workspace = true
serde_json.workspace = true

kaspa-txscript.workspace = true
kaspa-addresses.workspace = true
kaspa-hashes.workspace = true
kaspa-consensus-core.workspace = true

daglock-contracts = { path = "../contracts" }
daglock-shared = { path = "../shared" }
blake2b_simd.workspace = true
hex.workspace = true

[package.metadata.wasm-pack]
profile = "release"
scope = "daglock"
